const qs_list = [
//cat. 電気, 情報, 通信, 一般

//[General],
["ATM", "Automated Teller Machine","現金自動預け払い機"],
["ETC", "Electronic Toll Collection","道路通行料自動徴収システム"],
["VTR", "Videotape Recorder", "録画機"],
["OHP", "Overhead Projector", "投影機"],
["OCR", "Optical Character (Reader|Recognition)", "光学文字認識(装置)"],
["POSシステム", "Point of Sale", "販売時点情報管理"],

["PETボトル", "Polyethylene Terephthalate", "合成樹脂の一"],
["NOx", "Nitrogen Oxide", "窒素酸化物"],
["TNT", "Trinitrotoluene", "火薬の一"],
["CFC", "Chlorofluorocarbon", "フロン, フッ素化合物の一"],

["ICPO", "International Criminal Police Organization", "国際刑事警察機構"],
["CIA", "Central Intelligence Agency", "(アメリカの)中央情報局"],
["FBI", "Federal Bureau (of )Investigation","連邦捜査局"],
["GDP", "Gross Domestic Product","国内総生産"],
["GNP", "Gross National Product","国民総生産"],
["GHQ", "General Headquarter(s)", "(連合軍の)総司令部"],
["ICU", "Intensive Care Unit","集中治療室"],
["IMF", "International Monetary Fund","国際通貨基金"],
["IAEA", "International Atomic Energy Agency","国際原子力機関"],
["ODA", "Official Development Assistance", "政府開発援助"],
["NASA", "National Aeronautics (and )Space Administration", "アメリカ航空宇宙局"],
["NATO", "North Atlantic Treaty Organization", "北大西洋条約機構"],
["PKO", "Peacekeeping Operation(s)", "(国連の)平和維持活動"],
["UNICEF", "United Nations Children's Fund", "国際連合児童基金"],
["UNESCO", "United Nations Educational, Scientific (and )Cultural Organization", "国際連合教育科学文化機関"],
["ASEAN", "Association (of )South-East Asian Nation(s)","東南アジア諸国連合"],
["NEET", "Not (in )Education, Employment (or )Training", "若年無業者"],
["SDGs", "Sustainable Development Goal(s)", "持続可能な開発目標"],
["PDCAサイクル", "Plan-Do-Check-Act", "品質管理の手法"],

["AI", "Artificial Intelligence", "人工知能"],
["BS", "Broadcast(ing) Satellite","放送衛星"],
["CEO", "Chief Executive Officer","経営最高責任者"],
["CATV","Cable Television", "有線放送"],
["FM", "Frequency Modulation", "周波数変調"],
["IQ", "Intelligence Quotient", "知能指数"],
["ISBN", "International Standard Book Number", "国際標準図書番号"],
["JAS", "Japanese Agricultural Standard", "日本農林規格"],
["OJT", "On(-the)-Job Training","実地研修"],
["OS", "Operating System", "UnixやらWindowsやら"],
["POP", "Point of Purchase","店頭広告"],
["PR", "Public Relation(s)", "宣伝活動"],
["QRコード", "Quick Response", "マトリクス型2次元バーコード"],
["SL", "Steam Locomotive", "蒸気機関車"],
["VIP", "Very Important Person", "要人"],
["UFO", "Unidentified Flying Object", "未確認飛行物体"],
["SNS", "Social Networking Service", "社会交流のためのウェブサービス"],
["LCC", "Low-cost Carrier", "格安航空会社"],

//["DTM", "Desktop Music", "コンピュータ音楽制作(和製英語)"],
["BGM", "Background Music", "劇伴音楽"],
["MIDI", "Musical Instrument Digital Interface", "楽曲データ規格の一"],
["BPM", "Beat(s) Per Minute", "演奏テンポ"],
["MTR", "Multi Track Recorder", "多重録音機"],
["DJ", "Disc Jockey", "選曲者"],

["MVP", "Most Valuable Player", "最優秀選手"],
["TKO", "Technical Knock Out", "ボクシングの棄権"],
["SF映画", "Science Fiction"],
["CMソング", "Commercial Message"],
["AV機器", "Audio Visual"],
["RPG", "Role-Playing Game","コンピュータゲームの一"],
["FPS", "First Person (Shooter|Shooting)","コンピュータゲームの一"],

["WHO", "World Health Organization", "世界保健機関"],
["CTスキャン", "Computed Tomography", "コンピュータ断層撮影"],
["MRI", "magnetic resonance imaging", "核磁気共鳴画像法"],
["BSE", "Bovine Spongiform Encephalopathy", "牛海綿状脳症"],
["AIDS", "Acquired (Immune |Immuno-)Deficiency Syndrome", "後天性免疫不全症候群"],
["HIV", "Human Immuno(-)deficiency Virus", "ヒト免疫不全ウイルス"],
["REM睡眠", "Rapid Eye Movement"],

["IT", "Information Technology", "情報技術"],
["IoT", "Internet of Things", "モノのインターネット"],
["TBD", "To Be Determined", "未定"],

//"AC/DCアダプタ"
["OEM", "Original Equipment Manufacturer", "他社の商標をつけた製品製造"],
["BOM", "Bill of material(s)", "部品表"],
["UTC", "Coordinated Universal Time", "協定世界時"],
["GMT", "Greenwich Mean Time", "グリニッジ標準時"],
["VHS", "Video Home System", "動画記録方式"],
["FAT", "File Allocation Table", "DOSのファイルシステム"],
["VGA", "Video Graphics Array", "640×480画素"],
["XGA", "Extended Graphics Array", "1024×768画素"],
["MIPS", "Million Instruction(s) Per Second", "処理速度の単位"],
["MTBF", "Mean Time Between Failure(s)", "平均故障間隔"],

//[org],
["W3C", "World Wide Web Consortium","標準化団体の一"],
["IETF", "Internet Engineering Task Force", "標準化団体の一"],
["RFC", "Request for Comment(s)", "IETF発行の技術仕様文書"],
["ISO", "International Organization (for )Standardization", "国際標準化機構"],
["JIS", "Japanese Industrial Standards", "日本工業規格"],
["ANSI", "American National Standards Institute", "米国国家規格協会"],
["IEEE", "(The )*Institute (of )Electrical (and )Electronics Engineer(s)(, Inc.)*", "学会・標準化団体の一"],
["VCCI", "Voluntary Control Council (for )Interference( by Information Technology Equipment)*", "標準化団体の一"],
["RoHS", "Restriction of Hazardous Substance(s)", "有害物質制限の指令"],
 // ["PSE", "Product Safety Electrical Appliance & Material", "電気用品安全法"],
["ITU", "International Telecommunication Union", "国際電気通信連合"],

//[Circuit],
["SNR", "Signal(-to)*-Noise Ratio", "信号雑音比"],
["RMS", "Root Mean Square","実効値"],
["VVVF", "Variable Voltage Variable Frequency", "可変電圧・可変周波数制御(和製英語)"],
["RTC", "Real Time Clock","コンピュータの内部時計"],
["LED", "Light Emitting Diode", "発光素子の一"],
["RAM", "Random Access Memory","記憶素子の一"],
["ROM", "Read Only Memory","記憶素子の一"],
["DRAM", "Dynamic Random Access Memory","記憶素子の一"],
["SRAM", "Static Random Access Memory","記憶素子の一"],
["EEPROM", "Electrically Erasable Programmable Read-Only Memory","記憶素子の一"],
["FPGA", "Field-Programmable Gate Array","集積回路の一"],
["FET", "Field Effect Transistor","スイッチング素子"],
["DIP", "Dual In-line Package", "電子部品パッケージの一"],
["CMOS", "Complementary Metal-Oxide Semiconductor", "半導体素子の一"],
["MEMS", "Micro-Electro-Mechanical System(s)", "微小電気機械素子"],
["CPU", "Central Processing Unit","中枢演算処理装置"],
["ASIC", "Application Specific Integrated Circuit","集積回路の一"],
["SoC", "System-on(-a)-Chip", "集積回路の一方式"],
["LSI", "Large Scale Integration", "集積回路の一"],
["TTL", "Transistor-Transistor Logic", "集積回路の一"],
["LCD", "Liquid Crystal Display","液晶画面"],
["BGA", "Ball Grid Array","電子部品のパッケージの一"],
["DUT", "Device Under Test","検査対象"],
["PLL", "Phase Locked Loop","位相同期回路"],
["RFID", "Radio Frequency Identification", "記録用非接触カードとか"],
["SEM", "Scanning Electron Microscope","走査型電子顕微鏡"],
["USB", "Universal Serial Bus","機器間接続インタフェイスの一"],
["HDMI", "High-Definition Multimedia Interface", "機器間接続インタフェイスの一"],
["SATA", "Serial Advanced Technology Attachment","コンピュータと補助記憶装置との接続方式の一"],
["CAD", "Computer Aided Design", "設計ソフトとか"],
["FPC", "Flexible Printed Circuit","回路基板の一"],
["PCB", "Printed Circuit Board","回路基板"],
["WDT", "Watch(-)*Dog Timer", "動作時間監視デバイス"],
["TRON", "The Real-time Operating system Nucleus", "コンピュータアーキテクチャの策定プロジェクト"],
["BIOS", "Basic Input/Output System","ファームウェアの一"],
["EMI", "Electro-Magnetic Interference","電磁波障害"],
["DDR", "Double-Data-Rate", "コンピュータ用メモリの一規格"],
["SCSI", "Small Computer System Interface", "機器間接続インタフェイスの一"],
["HDD", "Hard Disk Drive","記憶装置の一"],
["RAID", "Redundant Array(s)* (of )(Inexpensive|Independent) Disk(s)", "記憶装置の冗長運用手法"],
["NAS", "Network Attached Storage", "接続網上の記憶装置"],
["SSD", "Solid State Drive", "記憶装置の一"],
["RTOS", "Real-time Operating System"],
["MODEM", "Modulator/Demodulator", "変調復調装置"],
["PWM", "Pulse Width Modulation", "パルス幅変調"],
["VHF", "Very High Frequency", "超短波"],
["UPS", "Uninterruptible Power Supply", "無停電電源装置"],
["PCI", "Peripheral Component Interconnect", "PC内部の接続インタフェイスの一"],
["LASER", "Light Amplification (by )Stimulated Emission (of )Radiation", "輻射の誘導放出による光増幅"],

//[Analyze/Prg],
["FFT", "Fast Fourier Transform","アルゴリズム, 高速フーリエ変換"],
["FEM", "Finite Element Method","数値計算手法, 有限要素法"],
["IDE", "Integrated Development Environment","統合開発環境"],
["API", "Application Programming Interface","外部公開関数"],
["SDK", "Software Development Kit","開発ツール"],
["GUI", "Graphical User Interface", "直感的な操作画面"],
["DLL", "Dynamic Link Library", "汎用プログラム集"],
["OOP", "Object Oriented Programming","プログラミング手法の一"],
["CRC", "Cyclic Redundancy Check", "巡回冗長検査"],
["BER", "Bit Error (Rate|Ratio)","データ誤り率"],
["CODEC", "COder/DECoder", "符号化と復号"],
["COBOL", "Common Business Oriented Language", "プログラミング言語の一"],
["FORTRAN", "Formula Translation", "プログラミング言語の一"],
["LISP", "List Processing", "プログラミング言語の一"],
["NaN", "Not a Number", "非数"],
["FIFO", "First In, First Out", "格納順にデータを取り出すこと"],
["OSS", "Open-Source Software", "ソース開示ソフト"],
["UML", "Unified Modeling Language", "ソフトウェア設計図の表記法, 統一モデリング言語"],
["RDBMS", "Relational Database Management System", "関係データベース管理システム"],
["GPL", "(GNU )General Public License", "GNUのソフト利用許諾"],
["SQL", "Structured Query Language", "データベース操作用言語"],

//[Web],
["URL", "Uniform Resource Locator","ウェブ上の住所を示す記述方式"],
["XML", "Extensible Markup Language","タグ言語の一"],
["BBS", "Bulletin Board System","掲示板"],
["CGI", "Common Gateway Interface","ウェブページの動的生成処理"],
["CSS", "Cascading Style Sheet(s)","ウェブページの修飾指定"],
//["Ajax", "Asynchronous JavaScript(+XML)","ウェブページの動的生成処理"],
["EUC", "Extended Unix Code","文字コード"],
["ASCII", "American Standard Code (for )Information Interchange","文字コード"],
["FAQ", "Frequently Asked Question(s)","頻出質問集"],
["WWW", "World Wide Web", "インタネット上の文書システム"],
["RDF", "Resource Description Framework", "ウェブ情報記述方式の枠組み"],
["SNS", "Social Networking Service", "ウェブ上の交流サイト"],

["IME", "Input Method Editor", "多言語文字入力ソフト"],
["PDF", "Portable Document Format", "文書ファイル規格"],
["GIF", "Graphic(s) Interchange Format", "画像ファイル規格"],
["JPEG", "Joint Photographic Expert(s) Group", "画像ファイル規格"],
["MPEG", "Moving Picture Expert(s) Group", "動画ファイル規格"],
["PNG", "Portable Network Graphic(s)", "画像ファイル規格"],
["TAR", "Tape Archive(s)", "ファイル圧縮形式"],
["CSV", "Comma-Separated Value(s)", "コンマ区切りデータ"],
["WYSIWYG", "What You See Is What You Get","編集画面と出力結果が一致する"],

//[Net],
["SIM", "Subscriber Identity Module", "携帯電話の認証装置"],
["RADIUS", "Remote Authentication Dial In User Service", "インタネット上のユーザ認証プロトコル"],
["Wi-Fi", "Wireless Fidelity", "無線通信規格の一"],
["WiMAX", "Worldwide Interoperability (for )Microwave Access", "無線通信規格の一"],
["LAN", "Local Area Network", "小規模なコンピュータ接続網"],
["WAN", "Wide Area Network", "広範囲なコンピュータ接続網"],
["QoS", "Quality of Service", "通信帯域確保"],
["MACアドレス",  "Media Access Control", "データリンク層の一部"],
["DHCP", "Dynamic Host Configuration Protocol", "機器にアドレスなどを割り当てる仕組み"],
["DNS", "Domain Name System", "ホスト名とアドレスを対応させる仕組み"],
["ARP", "Address Resolution Protocol", "アドレス解決用の通信規定"],
["IPアドレス", "Internet Protocol" ],
["TCP", "Transmission Control Protocol","伝送制御の仕組み"],
["UDP", "User Datagram Protocol", "(ネットワーク用語)"],
["DOS攻撃", "Denial of Service",""],
["FTP", "File Transfer Protocol", "ファイル転送用の通信規定"],
["HTTP", "Hypertext Transfer Protocol", "ウェブサイトのデータ送受用の通信規定"],
["SSH", "Secure Shell", "暗号化を用いた遠隔操作プロトコル"],
["NTP", "Network Time Protocol", "時刻合わせ用の通信規定"],
["SIP", "Session Initiation Protocol", "セッション確立用の通信規定"],
["SNMP", "Simple Network Management Protocol", "遠隔監視用の通信規定"],
["SMTP", "Simple Mail Transfer Protocol", "メール送信用の通信規定"],
["POP3", "Post Office Protocol", "メール受信用の通信規定"],
["PPPoE", "Point-to-Point Protocol over Ethernet", "2地点間のイーサネット接続"],
["PoE", "Power over Ethernet", "LANケーブルによる給電"],
["ADSL", "Asymmetric Digital Subscriber Line", "電話線を用いた高速通信技術"],
["MIME", "Multipurpose Internet Mail Extension(s)", "電子メールで多数のファイル規格を扱うための規格"],
["SSL", "Secure Socket(s) Layer", "データを暗号化して送受するプロトコル"],
["ICMP", "Internet Control Message Protocol", "pingコマンドとか"],
["VPN", "Virtual Private Network", "仮想的な組織内コンピュータ接続網"],
["FTTH", "Fiber To The Home", "一般家庭向け光ファイバ通信サービス"],
["NAT", "Network Address Translation", "ルータなどのIP変換機能"],
["LTE", "Long Term Evolution","携帯電話の通信規格"],
["TLD", "Top Level Domain", ".jpやら.comやら"],
["PHS", "Personal Handyphone System","携帯端末の一"],
["GPS", "Global Positioning System","全地球測位網"],
["ISDN", "Integrated Service(s) Digital Network", "サービス総合ディジタル網"],
["GE-PON","Gigabit Ethernet-Passive Optical Network", "光ファイバによる1Gbps通信"],
["OCN", "Open Computer Network", "インタネットプロバイダの一"],

["WDM", "Wavelength-Division Multiplex(ing)", "波長分割多重"],
["OFDM", "Orthogonal Frequency-Division Multiplex(ing)", "直交周波数分割多重方式"],
["PSK", "Phase-Shift Keying","位相偏移変調"],
["PSK", "Pre-Shared Key", "事前共有鍵"],
["CDMA", "Code Division Multiple Access", "符号分割多元接続"],
["WEP", "Wired Equivalent Privacy", "無線通信用の暗号化技術"],
["ESSID", "Extended Service Set Identifier", "無線LANのネットワーク識別子"], 

["RS-232", "Recommended Standard", "機器間接続インタフェイスの一"],
["RJ-45", "Registered Jack", "LANケーブルなどのコネクタ"],
["UTPケーブル", "Unshielded Twisted Pair", "LANケーブルなどの配線構造"],
["UPnP", "Universal Plug and Play", "機器接続時にネットワーク接続する技術"]
];
